In [ ]:
import numpy as np

array1 = np.array([1, 2, 3])
print(f'array1 type: {type(array1)}')
print(f'array1 shape: {array1.shape}')

array2 = np.array([[1, 2, 3], [4, 5, 6]])
print(f'array2 type: {type(array2)}')
print(f'array2 shape: {array2.shape}')

array3 = np.array([[1, 2, 3]])
print(f'array3 type: {type(array3)}')
print(f'array3 shape: {array3.shape}')

array1 type: <class 'numpy.ndarray'>
array1 shape: (3,)
array2 type: <class 'numpy.ndarray'>
array2 shape: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 shape: (1, 3)


In [ ]:
print(f'{array1.ndim}차원') # array1의 차원: 1차원
print(f'{array2.ndim}차원') # array2의 차원: 2차원
print(f'{array3.ndim}차원') # array3의 차원: 2차원

1차원
2차원
2차원


In [ ]:
list1 = [1, 2, 4]
print(type(list1)) # 원본 리스트의 타입: <class 'list'>

array1 = np.array(list1)
print(type(array1)) # 변환된 NumPy 배열의 타입: <class 'numpy.ndarray'>
print(array1, array1.dtype) # 배열의 값과 데이터 타입 출력: [1 2 4] int64

<class 'list'>
<class 'numpy.ndarray'>
[1 2 4] int64


In [ ]:
list2 = [2, 3, 'list']
array2 = np.array(list2)
print(array2, array2.dtype) # ['2' '3' 'list'] <U21 (유니코드 문자열)

list3 = [2, 3, 4.0]
array3 = np.array(list3)
print(array3, array3.dtype) # [2. 3. 4.] float64

list4 = [1, True, 0, False]
array4 = np.array(list4)
print(f'array4: {array4}, dtype: {array4.dtype}') # [1 1 0 0] int64 (True는 1, False는 0으로 변환)

['2' '3' 'list'] <U21
[2. 3. 4.] float64
array4: [1 1 0 0], dtype: int64


In [ ]:
array_int = np.array([1, 2, 3])
print(f'원본 정수형 배열: {array_int}, dtype: {array_int.dtype}')

array_float = array_int.astype('float64')
print(f'float64로 변경된 배열: {array_float}, dtype: {array_float.dtype}') # [1. 2. 3.] float64

array_int1 = array_float.astype('int32')
print(f'int32로 변경된 배열: {array_int1}, dtype: {array_int1.dtype}') # [1 2 3] int32

array_str = np.array(['10', '20', '30'])
array_int_from_str = array_str.astype('int')
print(f'문자열을 int로 변경: {array_int_from_str}, dtype: {array_int_from_str.dtype}')

원본 정수형 배열: [1 2 3], dtype: int64
float64로 변경된 배열: [1. 2. 3.], dtype: float64
int32로 변경된 배열: [1 2 3], dtype: int32
문자열을 int로 변경: [10 20 30], dtype: int64


In [ ]:
zeros_int_array = np.zeros((2, 3), dtype='int')
print(f"int형 zeros 배열:\n{zeros_int_array}\ndtype: {zeros_int_array.dtype}\n")

ones_float_array = np.ones((3, 2), dtype='float')
print(f"float형 ones 배열:\n{ones_float_array}\ndtype: {ones_float_array.dtype}")

int형 zeros 배열:
[[0 0 0]
 [0 0 0]]
dtype: int64

float형 ones 배열:
[[1. 1.]
 [1. 1.]
 [1. 1.]]
dtype: float64


In [ ]:
original_array = np.array([1, 2, 3, 4, 5])
print(f"원본 배열: {original_array}\ndtype: {original_array.dtype}\n")

float_array = original_array.astype('float64')
print(f"float64로 변경:\n{float_array}\ndtype: {float_array.dtype}\n")

string_array = original_array.astype('str')
print(f"str로 변경:\n{string_array}\ndtype: {string_array.dtype}\n")

float_to_int_array = np.array([1.5, 2.7, 3.1])
int_from_float_array = float_to_int_array.astype('int32')
print(f"float => int32로 변경 (소수점 버림):\n{int_from_float_array}\ndtype: {int_from_float_array.dtype}")

bool_array = np.array([0, 1, -5, 0.0, 0.1])
bool_converted_array = bool_array.astype('bool')
print(f"\nbool로 변경: {bool_converted_array}\ndtype: {bool_converted_array.dtype}")

원본 배열: [1 2 3 4 5]
dtype: int64

float64로 변경:
[1. 2. 3. 4. 5.]
dtype: float64

str로 변경:
['1' '2' '3' '4' '5']
dtype: <U21

float => int32로 변경 (소수점 버림):
[1 2 3]
dtype: int32

bool로 변경: [False  True  True False  True]
dtype: bool


In [ ]:
array_1d = np.arange(12)
print(f"원본 1차원 배열:\n{array_1d}\nshape: {array_1d.shape}\n")

reshaped_3x4 = array_1d.reshape(3, 4)
print(f"3X4로 재구성된 배열:\n{reshaped_3x4}\nshape: {reshaped_3x4.shape}\n")

reshaped_2x6 = array_1d.reshape(2, 6)
print(f"2X6로 재구성된 배열:\n{reshaped_2x6}\nshape: {reshaped_2x6.shape}\n")

reshaped_4x_1 = array_1d.reshape(4, -1)
print(f"4X?로 재구성된 배열 (자동 계산):\n{reshaped_4x_1}\nshape: {reshaped_4x_1.shape}\n")

reshaped_3d = array_1d.reshape(2, 2, 3)
print(f"2X2X3 3차원 배열:\n{reshaped_3d}\nshape: {reshaped_3d.shape}")

원본 1차원 배열:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
shape: (12,)

3X4로 재구성된 배열:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
shape: (3, 4)

2X6로 재구성된 배열:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
shape: (2, 6)

4X?로 재구성된 배열 (자동 계산):
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
shape: (4, 3)

2X2X3 3차원 배열:
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
shape: (2, 2, 3)


In [ ]:
array1 = np.arange(1, 10) # [1 2 3 4 5 6 7 8 9]
array2d = array1.reshape(3, 3) # [[1 2 3], [4 5 6], [7 8 9]]

print(f'array1의 3번째 요소 (인덱스 2): {array1[2]}\n') # 3
print(f'array1의 마지막 요소 (음수 인덱싱): {array1[-1]}\n') # 9
print(f'array1의 마지막에서 두 번째 요소: {array1[-2]}\n') # 8

print(f'array2d의 첫 번째 행, 첫 번째 열 요소: {array2d[0, 0]}\n') # 1
print(f'array2d의 두 번째 행, 세 번째 열 요소: {array2d[1, 2]}') # 6

array1의 3번째 요소 (인덱스 2): 3

array1의 마지막 요소 (음수 인덱싱): 9

array1의 마지막에서 두 번째 요소: 8

array2d의 첫 번째 행, 첫 번째 열 요소: 1

array2d의 두 번째 행, 세 번째 열 요소: 6


In [ ]:
print(f'array1의 인덱스 0부터 2까지 (3은 포함 안 함): {array1[0:3]}\n') # [1 2 3]
print(f'array1의 처음부터 인덱스 2까지 (3은 포함 안 함): {array1[:3]}\n') # [1 2 3]
print(f'array1의 인덱스 3부터 끝까지: {array1[3:]}\n') # [4 5 6 7 8 9]
print(f'array1의 전체: {array1[:]}') # [1 2 3 4 5 6 7 8 9]

print(f'array2d의 [0:2, 0:2] 슬라이싱:\n{array2d[0:2, 0:2]}\n') # [[1 2], [4 5]]

print(f'array2d의 [1:3, :] 슬라이싱:\n{array2d[1:3, :]}\n') # [[4 5 6], [7 8 9]]

print(f'array2d의 [:2, 1:] 슬라이싱:\n{array2d[:2, 1:]}') # [[2 3], [5 6]]

array1의 인덱스 0부터 2까지 (3은 포함 안 함): [1 2 3]

array1의 처음부터 인덱스 2까지 (3은 포함 안 함): [1 2 3]

array1의 인덱스 3부터 끝까지: [4 5 6 7 8 9]

array1의 전체: [1 2 3 4 5 6 7 8 9]
array2d의 [0:2, 0:2] 슬라이싱:
[[1 2]
 [4 5]]

array2d의 [1:3, :] 슬라이싱:
[[4 5 6]
 [7 8 9]]

array2d의 [:2, 1:] 슬라이싱:
[[2 3]
 [5 6]]


In [ ]:
print(f'array2d[[0,1], 2] (첫 번째/두 번째 행의 세 번째 열): {array2d[[0,1], 2]}\n') # [3 6]

print(f'array2d[[0,1], 0:2] (첫 번째/두 번째 행의 첫 번째/두 번째 열):\n{array2d[[0,1], 0:2]}\n') # [[1 2], [4 5]]

print(f'array2d[[0,1]] (첫 번째/두 번째 행 전체):\n{array2d[[0,1]]}') # [[1 2 3], [4 5 6]]

array2d[[0,1], 2] (첫 번째/두 번째 행의 세 번째 열): [3 6]

array2d[[0,1], 0:2] (첫 번째/두 번째 행의 첫 번째/두 번째 열):
[[1 2]
 [4 5]]

array2d[[0,1]] (첫 번째/두 번째 행 전체):
[[1 2 3]
 [4 5 6]]


In [ ]:
print(f'array1[array1 > 5] (5보다 큰 요소): {array1[array1 > 5]}') # [6 7 8 9]

even_numbers = array1[array1 % 2 == 0]
print(f'array1에서 짝수만: {even_numbers}')

array1[array1 > 5] (5보다 큰 요소): [6 7 8 9]
array1에서 짝수만: [2 4 6 8]


In [ ]:
org_array = [1, 3, 4, 2, 5, 6, 8]

print(f'오름차순 정렬: {np.sort(org_array)}') # [1 2 3 4 5 6 8]

print(f'내림차순 정렬: {np.sort(org_array)[::-1]}') # [8 6 5 4 3 2 1]

오름차순 정렬: [1 2 3 4 5 6 8]
내림차순 정렬: [8 6 5 4 3 2 1]


In [ ]:
print(f'axis=0 (열 방향) 정렬:\n{np.sort(array2d, axis=0)}\n')

print(f'axis=1 (행 방향) 정렬:\n{np.sort(array2d, axis=1)}')

unsorted_array2d = np.array([[9, 3, 6], [1, 8, 2], [7, 4, 5]])
print(f'\n원본 2차원 배열:\n{unsorted_array2d}\n')

print(f'axis=0 (열 방향) 정렬:\n{np.sort(unsorted_array2d, axis=0)}\n')

print(f'axis=1 (행 방향) 정렬:\n{np.sort(unsorted_array2d, axis=1)}')

axis=0 (열 방향) 정렬:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

axis=1 (행 방향) 정렬:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

원본 2차원 배열:
[[9 3 6]
 [1 8 2]
 [7 4 5]]

axis=0 (열 방향) 정렬:
[[1 3 2]
 [7 4 5]
 [9 8 6]]

axis=1 (행 방향) 정렬:
[[3 6 9]
 [1 2 8]
 [4 5 7]]


In [ ]:
score_array = np.array([78, 95, 84, 98, 88])
print(f'원본 배열: {score_array}\n')

sort_idx = np.argsort(score_array)
print(f'오름차순 정렬 시 인덱스: {sort_idx}') # [0 2 4 1 3]

sort_idx_desc = np.argsort(score_array)[::-1]
print(f'내림차순 정렬 시 인덱스: {sort_idx_desc}\n') # [3 1 4 2 0]

print(f'오름차순으로 정렬된 값: {score_array[sort_idx]}')
print(f'내림차순으로 정렬된 값: {score_array[sort_idx_desc]}')

원본 배열: [78 95 84 98 88]

오름차순 정렬 시 인덱스: [0 2 4 1 3]
내림차순 정렬 시 인덱스: [3 1 4 2 0]

오름차순으로 정렬된 값: [78 84 88 95 98]
내림차순으로 정렬된 값: [98 95 88 84 78]
